public class Main {
	public static void main(String[] args) {
		BooleanGames game1 = new BooleanGames(10);
		System.out.println(game1.isNegative());
		System.out.println("----");
		System.out.println(game1.exceeds(9));
		System.out.println(game1.exceeds(10));
		System.out.println(game1.exceeds(11));
		System.out.println("----");
		System.out.println(game1.isEven());
		System.out.println(game1.isOdd());
		System.out.println("----");
		System.out.println(game1.isMultipleOf(1));
		System.out.println(game1.isMultipleOf(2));
		System.out.println(game1.isMultipleOf(5));
		System.out.println(game1.isMultipleOf(10));
		System.out.println(game1.isMultipleOf(4));
		System.out.println(game1.isMultipleOf(8));
		System.out.println(game1.isMultipleOf(20));
		System.out.println("----");
		System.out.println(game1.isOnesDigit(0));
		System.out.println(game1.isOnesDigit(1));
		System.out.println(game1.isOnesDigit(5));

		BooleanGames game2 = new BooleanGames(-15);
		System.out.println(game2.isNegative());
		System.out.println("----");
		System.out.println(game2.exceeds(-20));
		System.out.println(game2.exceeds(-15));
		System.out.println(game2.exceeds(0));
		System.out.println("----");
		System.out.println(game2.isEven());
		System.out.println(game2.isOdd());
		System.out.println("----");
		System.out.println(game2.isMultipleOf(1));
		System.out.println(game2.isMultipleOf(3));
		System.out.println(game2.isMultipleOf(5));
		System.out.println(game2.isMultipleOf(15));
		System.out.println(game2.isMultipleOf(10));
		System.out.println(game2.isMultipleOf(2));
		System.out.println(game2.isMultipleOf(30));
		System.out.println("----");
		System.out.println(game2.isOnesDigit(5));
		System.out.println(game2.isOnesDigit(1));
		System.out.println(game2.isOnesDigit(6));

		BooleanGames game3 = new BooleanGames(7283);
		System.out.println(game3.isNegative());
		System.out.println("----");
		System.out.println(game3.exceeds(7000));
		System.out.println(game3.exceeds(7283));
		System.out.println(game3.exceeds(7500));
		System.out.println("----");
		System.out.println(game3.isEven());
		System.out.println(game3.isOdd());
		System.out.println("----");
		System.out.println(game3.isMultipleOf(1));
		System.out.println(game3.isMultipleOf(3));
		System.out.println(game3.isMultipleOf(7));
		System.out.println(game3.isMultipleOf(13));
		System.out.println(game3.isMultipleOf(10));
		System.out.println("----");
		System.out.println(game3.isOnesDigit(3));
		System.out.println(game3.isOnesDigit(8));
		System.out.println(game3.isOnesDigit(2));
		System.out.println(game3.isOnesDigit(7));
		System.out.println(game3.isOnesDigit(5));

		BooleanGames game4 = new BooleanGames(-435);
		System.out.println(game4.isNegative());
		System.out.println("----");
		System.out.println(game4.exceeds(-600));
		System.out.println(game4.exceeds(-500));
		System.out.println(game4.exceeds(0));
		System.out.println("----");
		System.out.println(game4.isEven());
		System.out.println(game4.isOdd());
		System.out.println("----");
		System.out.println(game4.isMultipleOf(1));
		System.out.println(game4.isMultipleOf(2));
		System.out.println(game4.isMultipleOf(3));
		System.out.println(game4.isMultipleOf(5));
		System.out.println(game4.isMultipleOf(35));
		System.out.println(game4.isMultipleOf(145));
		System.out.println(game4.isMultipleOf(435));
		System.out.println("----");
		System.out.println(game4.isOnesDigit(5));
		System.out.println(game4.isOnesDigit(3));
		System.out.println(game4.isOnesDigit(4));
		System.out.println(game4.isOnesDigit(0));
		System.out.println(game4.isOnesDigit(35));
	}
}
